### ISSUE TITLE
Too high on-heap memory and GC overhead 

### ISSUE THREAD

**Issue by l15k4** [densh/scala-offheap#114]
Hey, 

I think that the value classes that hold allocation address put significant on-heap memory and GC overhead : 
```scala
import scala.offheap
object Play extends App {
  implicit val alloc = offheap.malloc
  val arr = new scala.Array[offheap.Array[Byte]](Int.MaxValue/16)
  var counter = 0
  while (counter < Int.MaxValue/16) {
    arr(counter) = offheap.Array.fromArray("foobar".getBytes)
    counter+=1
  }
}
```

This ends up with `java.lang.OutOfMemoryError: GC overhead limit exceeded` even if I use `-Xmx4096` even though theoretically it should need only `Int.MaxValue/16 * 8` so `-Xmx2048m` tops

If I measure the resulting Array using [SizeEstimator.scala](https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/util/SizeEstimator.scala) it has `3758MB` which is `27B` per element, which is a `offheap.Array` value class that should break down to 8 bytes long only but it obviously doesn't.

It's probably my misuse of scala Value Classes, I think that if I do this `scala.Array[offheap.Array[Byte]](x,y,z)` then it doesn't matter then `offheap.Array` is a value class and it breaks down to a normal `x, y, z` instances on heap which I didn't expect to happen.

```
$ java -version
openjdk version "1.8.0_111"
OpenJDK Runtime Environment (build 1.8.0_111-8u111-b14-2ubuntu0.16.04.2-b14)
OpenJDK 64-Bit Server VM (build 25.111-b14, mixed mode)
```
And scala version from `scala-offheap` project

**Comment by DarkDimius** [comment]
Scala currently stores arrays of value classes in a boxed representation, and, I'd assume, that by the time scala-native comes, there's not much one can do with it. 

Dotty had a prototype in works that would support storing arrays of value classes efficiently 
https://github.com/lampepfl/dotty/pull/1228

**Comment by l15k4** [comment]
Yeah I just figured, that is a total bummer. It completely ruins all my plans I had with scala-offheap actually because what's the point of keeping stuff off-heap if it has a corresponding on-heap representation? Considering the fact that even "Offheap Classes" desugar down to value classes, scala-offheap has a very limited use case imho... It could have been a beginning of a beautiful friendship :-) 

Yeah dotty looks more and more promising !

**Comment by l15k4** [comment]
Good to know, thanks!
