### ISSUE TITLE
somewhere to discuss project

### ISSUE THREAD

**Issue by JohnMurray** [densh/scala-offheap#13]
Have you thought about setting up an IRC channel or using something like [Gitter](https://gitter.im/) (really popular with hipster developers these days)? Just thinking there could be some real interesting conversation around a project like this and it would be nice to have it in a central place that is easy to talk in / read.

If you use Gitter, you can put some cute badge on your `README.md` so people can click it and jump right into chat. The [Spray](https://github.com/spray/spray) project is a good example of this.

**Comment by densh** [comment]
Sounds great, lets do that.
