### ISSUE TITLE
Consider backporting the library to 2.10

### ISSUE THREAD

**Issue by densh** [densh/scala-offheap#19]
At the moment scala-offheap only works on 2.11 only. If it won't complicate the code too much it might be worth it to back-port the library to 2.10. If you want this to happen sooner rather than later please comment on this issue.

**Comment by BrianLondon** [comment]
Shamelessly bumping this.  There are a few large frameworks that don't work with 2.11 yet.

**Comment by mdedetrich** [comment]
Considering to use scala-offheap for the scala json AST implementation (to improve performance of `.toSafe` and `.toFast` methods), however we cant use scala-offheap if it doesn't support Scala 2.10

**Comment by mdedetrich** [comment]
In reference to https://github.com/densh/scala-offheap/issues/19#issuecomment-190529052, for myself the issue is not that critical anymore due to https://github.com/densh/scala-offheap/issues/15 (I can't use offheap until it supports Strings)

**Comment by densh** [comment]
Given that 2.12 is going to be released soon, we don't have enough resources to invest in 2.10 support.
