### ISSUE TITLE
Annotation less definition

### ISSUE THREAD

**Issue by sirinath** [densh/scala-offheap#23]
Defining whether an object is on heap or off heap using annotation at the point of definition is not very continent:

 - Case class can be defined in another library
 - You need to use both on heap and off heap version

So the decision if you need a on heap or off heap object should be ideally left to the point where you allocate the object

**Comment by densh** [comment]
Unfortunately at this moment in time it's not possible to do this without changing the language. The goal of `scala-offheap` right now is to be the best *library* for off-heap memory. If the situation changes (e.g. more language extension points are exposed) we might change the way we do off-heap classes. I believe that annotations are the best way to do this right now even though they make it impossible to use the same class definition for both on-heap and off-heap allocations.

**Comment by densh** [comment]
**p.s.** One of the reasons to use annotations is a clean way to give user feedback if his class can not be used off-heap (and why precisely). There are quite a few restrictions right now. For example inability to have references from off-heap to on-heap types, limited kinds of definitions that be nested in off-heap classes etc.

**Comment by sirinath** [comment]
Cann't you have something like

`val a = Alloc[A]`?

**Comment by densh** [comment]
Macro annotation generates quite a lot of class-specific low-level code that is necessary to make off-heap classes work. Outside of macro-annotations there is no easy way to generate a definition and re-use it across multiple allocation call-sites. Not only you can't share generated you also can't get an AST of the class outside of current compilation unit which is necessary for rewriting.

**Comment by sirinath** [comment]
What I was thinking was in the line of having off heap allocators than treating / handling on heap and off heap objects differently. I don't know this might work in your case.

**Comment by densh** [comment]
Off-heap and on-heap are completely different on byte-code level. On-heap classes are regular JVM classes and off-heap ones are value classes over offfheap references. Generation of the value-class based representation can only be done with macro annotation (as it's the only practical way to do the required code generation at the moment.) We might explore unification of off-heap and on-heap classes in the future.

**Comment by sirinath** [comment]
Just food for thought. Thinking through how to do this in an unified way from the start maybe the best way to get about it. Wouldn't looking into be able to use on heap for off heap also be the better and easier way to go? Also no need to restrict your self to value classes. Maybe there is a different but easier way to do this.

**Comment by densh** [comment]
I'm quite certain that unification is not possible without changing the compiler and that's out of scope at the moment. It might be easier to change the language but we can't just add functionality on the whim, Scala is quite a big language already. Instead we'll do our best at making a nice *library* that makes due with tools we already have like macros, implicits, value classes etc.

**Comment by sirinath** [comment]
OK

**Comment by virtualirfan** [comment]
There were a bunch of nuggets in this thread that should end up on the wiki
or README. Copy paste? :-)

Irfan

**Comment by densh** [comment]
I've just enabled support for wikis, feel free to add stuff there.
