### ISSUE TITLE
Consider making zero-field data classes not allocate anything

### ISSUE THREAD

**Issue by densh** [densh/scala-offheap#33]
This has been [previously explored in rust](http://www.wabbo.org/blog/2014/03aug_09aug.html). Effectively zero-size data classes would become first-class equivalent of `Unit`. Allocation would not call `allocate` on allocator as followers of zero-size types are never followed. Fields of zero-size types are also zero-size making it very useful feature to augment specialisation. 

Unfortunately this has some non-trivial feature interactions wrt current layout machinery that might need a complete rewrite to support this. Right now there is no compelling use case to do this but the idea is quite interesting and might be explored in the future.

**Comment by DarkDimius** [comment]
I'd say that as zero-size data classes are observationally equivalent, they can simply be replaced by singleton objects. Which could be either stored on-heap or off-heap.
