### ISSUE TITLE
Consider adding support for references to on-heap objects

### ISSUE THREAD

**Issue by densh** [densh/scala-offheap#4]
Should be implementable with the help of JNI's global references that let one mark objects as non-collectable for a fixed period of time. It's not clear if overhead and distribution complications are going to be worth it.

**Comment by siriux** [comment]
What about having an additional array (or some kind of hash table) of real on-heap references, and you just point to this table from the off-heap objects? This of course, would be hidden under the implementation, and the user wouldn't see it.

This has the advantage of being extremely simple, and plays well with GC. On the other hand, you introduce one more indirection, but it might be really small in most cases. 

Also, it would be possible to de-duplicate references, saving some space on the table, and other optimizations.

What do you think?

**Comment by densh** [comment]
@siriux 

It does play well with GC but how do you clean it up? If you just add stuff to one global array and leave it there forever it means that those objects and their transitive closure will never be garbage collected. That's a memory leak in the making. 

It might be possible to make those arrays region-local though. But this will require some extra memory overhead to remember corresponding region for each allocated object. It's yet to be seen if the overhead of this is going to be worth it. I need to experiment with the idea.

**Comment by siriux** [comment]
@densh 

Sorry I didn't make it clear in the previous comment, but I was thinking about region-based allocation. In this case, you have one array per region, and when the region goes out of scope (or is explicitly deleted) you can clean the whole array too. In that case is really simple and there is almost no overhead (just a pointer from the region to the array, and maybe some other minor things).

In the case of independently allocated objects outside of regions it's more difficult, but I have some ideas. For example, you can do better than an array pointer per object if you have a single array for all independent objects (therefore you don't need a pointer in every object). Then, to allow GC, when you delete/free an object (and this operation is explicit, unlike GC) you can set all it's on-heap pointers to null. 

Even better, you can set the pointers to a special "Deleted Object" that marks this place on the array as free, and the following allocations can reuse these pointers.  The "Deleted Object" search can be optimized in many ways, as it's done by other allocators, databases, ... 

I hope its clearer now

**Comment by densh** [comment]
Impossible to implement efficiently, therefore we're not going to support his.
