### ISSUE TITLE
Document why nulls can not be assigned to off-heap classes

### ISSUE THREAD

**Issue by flock0** [densh/scala-offheap#58]
Right now it's not possible to assign `null` to a variable of a `@data` class. Is this intentional?

Example that leads to a compile time error:
```scala
import offheap._

@data class Data(x:Int)
object Test extends App {
  implicit val props = Region.Props()
  Region { implicit r =>
    val d: Data = null
  }
}
```

**Comment by densh** [comment]
Hi Florian, this is a side-effect of off-heap classes being compiled down to value classes. An equivalent of  `null` for value class `C` is `C.empty`. It's an automatically generated helper that gives you null-like value for given type. 

I'll keep this issue open until I cover this topic in the documentation.

**Comment by flock0** [comment]
Ah, I overlooked that, thanks!
