### ISSUE TITLE
malloc should throw OutOfMemoryError

### ISSUE THREAD

**Issue by densh** [densh/scala-offheap#59]
Right now `malloc` just redirects to underlying malloc without doing proper error checking.

**Comment by arosenberger** [comment]
Hi Denys,

The native implementation for the Unsafe.allocateMemory call should do this for you [and is documented in the Unsafe API as well]. The relevant code snippet is here:

  void* x = os::malloc(sz);
  if (x == NULL) {
    THROW_0(vmSymbols::java_lang_OutOfMemoryError());
  }

So I don't think you need to do anything explicit in the malloc.scala code, unless you want to catch the OOME and do something else with it. The same holds for Unsafe.reallocateMemory

**Comment by densh** [comment]
@arosenberger I'll double check on Monday. At least it needs a test to make sure that it does throw an exception if obscene amount of memory is requested.

**Comment by densh** [comment]
@arosenberger Does jemalloc binding throw OutOfMemoryError?

**Comment by arosenberger** [comment]
I believe I have it throw IllegalArgumentException - I can make it switch to OOME.
