### ISSUE TITLE
Introduce jemalloc allocator bindings

### ISSUE THREAD

**Issue by densh** [densh/scala-offheap#61]
This a ticket to document things that need to be done to merge [topic/jemalloc](https://github.com/densh/scala-offheap/commits/topic/jemalloc) branch.

* [x] modularize jemalloc into separate subproject
* [x] teach build infrastructure to automatically fetch and build latest jemalloc 
* [x] decide if we want to support JDK6 
* [x] decide if we want to support 32-bit environments 
* [x] `jemalloc.allocate` should throw `OutOfMemoryError` if memory can not be allocated
* [x] ensure that casting between `offheap.Size` to `size_t` and `offheap.Addr` and `void*` are correct and work both on 32-bit and 64-bit platforms
* [ ] figure out how to properly publish native binaries to sonatype 
* [ ] launch shell scripts from sbt 

The list doesn't contain mac support yet. It'll come later after we are done with linux build.

**Comment by densh** [comment]
@arosenberger maybe we can use something like git submodules to include jemalloc into our repo. I think [this is how Rust does it](https://github.com/rust-lang/rust/tree/master/src).

**Comment by arosenberger** [comment]
@densh is there a way to get Travis to run tests against a 32 bit image? I am working on the offheap.Size <-> size_t code and tests but only have a 64 bit that I develop on

**Comment by densh** [comment]
@arosenberger It looks like [32-bit travis environments are not supported](https://github.com/travis-ci/travis-ci/issues/986) at the moment. I think it's reasonable to not support 32-bit at first if it's troublesome but this needs to be documented.

**Comment by arosenberger** [comment]
I can add the size checks to the jni binding and add a unit test at least for x64 that [signed] long max value doesn't get truncated. We could potentially just spin up a 32 bit vm manually and perform the tests - not a repeatable CI, but provides verification at least. 

We could also consider adding logic on the java side of things to test whether the os is x86 or x64 and warn / throw if the check (int) size == size fails. That should allow for mocking out the platform at least

**Comment by densh** [comment]
Unfortunately if we neither CI nor use it regularly for development we can't really claim that it works. I think that for now we can put a static assert that checks that checks that build is happening on 64-bit system with comment explaining that x86 is not supported at the moment.

**Comment by densh** [comment]
64-bit tests that checks if it works properly in age cases is always welcome of course.

**Comment by arosenberger** [comment]
I will add a static assert to the jni binding and some additional logic / unit tests to the wrapper. Unfortunately I think the tests might not be the clearest since currently I have 'fail to malloc/realloc' tests that use some arbitrary large value 1L << 62

I was going to switch to throwing exceptions from the jni binding as opposed to Java and add some tests passing Long.MaxValue. So while we won't catch a custom exception type [e.g. RequestTooLarge, or just re-use IllegalArgumentException?] we will unfortunately still have to catch OOME, which sort of duplicates / conflicts with the existing tests for trying to allocate a too large [but still valid value] chunk of memory.

What do you think?

**Comment by densh** [comment]
Throwing exception from JNI side might overcomplicate it. Is there any way to avoid it and do the checks on Java side before things get to JNI? Maybe introduce some dummy only-for-tests bindings to avoid complicating the actual bindings? 

I think that  re-using IllegalArgumentException is fine for this use-case.  That's what region allocators do at the moment.

**Comment by arosenberger** [comment]
I can try to constrain things to the Java side, but the JNI environment has support for throwing exceptions  and I think it would be easier to have those checks there. So the jemalloc wrapper would be a very thin shell that just invokes the native methods. For example the sun.misc.Unsafe native implementation is what throws IllegalArgumentException and OutOfMemoryError via the JNI environment. I'll make the changes and submit a pull request for you to review. You can always reject if you prefer to handle things on the Java side.

**Comment by densh** [comment]
@arosenberger If you feel it's it indeed easier, go for it.

**Comment by densh** [comment]
@arosenberger I've rebased topic/jemalloc on top of latest master excluding all of the merge commits. Previous state of the branch is available in topic/jemalloc-pre-rebase.

**Comment by densh** [comment]
Historical summary of what happened in this issue:

1. @arosenberger did a great job at implementing bindings for jemalloc via JNI.
2. We were stuck with close to no tooling support to distribute and support this code on the JVM ecosystem. All the known ways are hack-ish and there is no proper way to do it. Neither `sbt` nor `maven` have any awareness of the native side of the JNI world.
3. Given that it's going to be to hard to maintain a JNI-based solution it was never merged and a better alternative never appeared on the horizon. 

This issue had a major impact on Scala Native's future as we've learned that there is no sane way to use JNI, this is why we want with our own interop layer (via `@extern object`-s). Ultimately, the conclusion is we can not support bindings to jemalloc on the JVM.
