### ISSUE TITLE
Optimize boolean arrays to use 1 bit per element rather than 1 byte

### ISSUE THREAD

**Issue by densh** [densh/scala-offheap#71]
Currently we use quite inefficient scheme for storing booleans in arrays storing 1 byte per element. It shouldn't be too hard to shrink that overhead to 1 bit per element.

**Comment by andreaTP** [comment]
:+1:

**Comment by densh** [comment]
Boolean arrays in C also use 1 byte per element. If we want to have C-friendly data layout we have to stick to this convention. I think it's better to have a separate BitSet implementation for this use case like the one @andreaTP has been working on.
